# Bra-ket notation

Bra-ket notation represents vectors, inner products, operators, and basis expansions in a form used throughout quantum mechanics.

## Exercises

:::{#exr-bra-ket-notation-basis-basis-finite-dimensional-hilbert-space}

Let $B = \{b_1, b_2,\cdots, b_n\}$ be a basis for a finite-dimensional Hilbert space $V$, and let $\{\left|i\right\rangle\}$ be the standard basis for $\mathbb{C}^n$. Consider the operator $$\hat{B} = \sum_{i=1}^n \left|b_i\right\rangle \left\langle i\right|.$$ What are the domain and range of $\hat{B}$?

:::

:::{#exr-bra-ket-notation-consider-can-you-interpret-expression-terms}

Let $\left|x\right\rangle \in \mathbb{C}^n$, and consider $$\left|\psi\right\rangle = \hat{B} \left|x\right\rangle.$$ Can you interpret this expression in terms of bases and expansion coefficients?

:::

:::{#exr-bra-ket-notation-overlap-matrix-expressed-operator-find-expression}

Show that $$\hat{S} = \sum_{ij} \left|i\right\rangle \left\langle{b}_i|{b}_j\right\rangle \left\langle j\right|.$$ This is the overlap matrix expressed as an operator. Find an expression for the basis coefficients $x_i$ in terms of the basis alone.

:::

::: {.content-visible when-profile="tutor"}

## Solutions

### Tutor note: Bra-ket notation

I think it is important that the students try to relate bra-ket notation to more standard linear algebra notation.

### Solution to @exr-bra-ket-notation-basis-basis-finite-dimensional-hilbert-space

The domain is $\mathbb{C}^n$, and the range is $V$. It takes vectors in $\mathbb{C}^n$ and moves them to $V$.

### Solution to @exr-bra-ket-notation-consider-can-you-interpret-expression-terms

The components $x_i = \left\langle i|x\right\rangle$ are the expansion coefficients of $\left|\psi\right\rangle$ in the basis $B$.

### Solution to @exr-bra-ket-notation-overlap-matrix-expressed-operator-find-expression

$\left|x\right\rangle = \hat{S}^{-1} \hat{B}^\dagger\left|\psi\right\rangle$.

:::
