# Gaussian elimination




## Exercises {.unnumbered}

:::{#exr-gaussian-elimination-compute-overlap-matrix-basis-basis-defined  level="intermediate"}
### Gaussian elimination and overlap matrix

Consider the two vectors

$$
\mathbf{v}_1=
\begin{pmatrix}
1\\
1\\
0
\end{pmatrix},
\qquad
\mathbf{v}_2=
\begin{pmatrix}
1\\
0\\
1
\end{pmatrix}.
$$

a. Compute the overlap matrix $S$ with elements

    $$
    S_{ij}=\mathbf{v}_i^T\mathbf{v}_j.
    $$

b. Verify that $S$ is symmetric.

c. Use Gaussian elimination on the augmented matrix $[S\,|\,I]$ to compute $S^{-1}$.

d. Verify your result by computing $SS^{-1}$.

:::



:::{#exr-gaussian-elimination-write-down-dual-basis}

Write down the dual basis of $B = \{\mathbf{b}_1,\mathbf{b}_2\}$.

:::

::: {#exr-gaussian-elimination-robert-beezer-consider-following-system-equations }

(Robert Beezer) Consider the following system of equations: 

$$
\begin{aligned}
    2 x_1 -3x_2 + x_3 + 7 x_4 &= 14\\
    2x_1 + 8x_2 - 4x_3 + 5x_4 &= -1\\
    x_1 + 3x_2 - 3x_3 &= 4\\
    -5 x_1 + 2x_2 + 3 x_3 + 4x_4 &= -19
\end{aligned}
$$ 

Use Gaussian elimination to find all possible solutions. Write the solution set using set notation.

:::

:::{#exr-gaussian-elimination-robert-beezer-find-all-possible-solutions}

(Robert Beezer) Find all possible solutions of the linear system 
$$
\begin{aligned}
    3 x_1 + 4 x_2 - x_3 + 2 x_4 &= 6 \\
    x_1 - 2 x_2 + 3 x_3 + x_4 &= 2 \\
    10 x_2 - 10 x_3 - x_4 &= 1
\end{aligned}
$$ 

Write down the solution set using set notation.

:::

:::{#exr-gaussian-elimination-robert-beezer-find-all-possible-solutions-2}

(Robert Beezer) Find all possible solutions of the linear system 
$$
\begin{aligned}
    2 x_1 + 4 x_2 + 5 x_3 + 7 x_4 &= -26 \\
    x_1 + 2x_2 + x_3 - x_4 &= -4 \\
    -2 x_1 - 4 x_2 + x_3 + 11 x_4 &= -10
\end{aligned}
$$ 

Write down the solution set using set notation.

:::

<!-- -->

:::{#exr-gaussian-elimination-basis-basis-matrix-whose-columns-precisely}

Let $\mathbf{b}_i$, $i=1,2,\cdots,n$ be a basis for $\mathbb{R}^n$. Let $$B = [\mathbf{b}_1, \mathbf{b}_2, \cdots, \mathbf{b}_n]$$ be the *basis matrix*, whose columns are precisely the $\mathbf{b}_i$. Explain that if $\mathbf{y} = x_1 \mathbf{b}_1 + \cdots + x_n \mathbf{b}_n$, then $$B \mathbf{x} = \mathbf{y}.$$ Solve for $\mathbf{x}$ using $B$ in symbols.

:::

:::{#exr-gaussian-elimination-linearly-independent-vectors-given-write-down}

Let $n$ linearly independent vectors $B = \{\mathbf{b}_1, \cdots,\mathbf{b}_n\}$ of $\mathbb{F}^n$ be given. Write down a formula for the dual basis in terms of the overlap matrix.

:::

::: {.content-visible when-profile="tutor"}

## Solutions {.unnumbered}


### Solution for @exr-gaussian-elimination-compute-overlap-matrix-basis-basis-defined {.unnumbered}

a. The overlap matrix is defined by

    $$
    S_{ij}=\mathbf{v}_i^T\mathbf{v}_j.
    $$

    We have

    $$
    \mathbf{v}_1^T\mathbf{v}_1=2,\qquad
    \mathbf{v}_1^T\mathbf{v}_2=1,\qquad
    \mathbf{v}_2^T\mathbf{v}_1=1,\qquad
    \mathbf{v}_2^T\mathbf{v}_2=2.
    $$

    Therefore,

    $$
    S=
    \begin{pmatrix}
    2&1\\
    1&2
    \end{pmatrix}.
    $$

b. Since

    $$
    S^T=
    \begin{pmatrix}
    2&1\\
    1&2
    \end{pmatrix}
    =S,
    $$

    the overlap matrix is symmetric.

c. To find the inverse, we perform Gaussian elimination on the augmented matrix

    $$
    \left[
    \begin{array}{cc|cc}
    2&1&1&0\\
    1&2&0&1
    \end{array}
    \right].
    $$

    Interchange the two rows:

    $$
    \left[
    \begin{array}{cc|cc}
    1&2&0&1\\
    2&1&1&0
    \end{array}
    \right].
    $$

    Now perform $R_2\leftarrow R_2-2R_1$:

    $$
    \left[
    \begin{array}{cc|cc}
    1&2&0&1\\
    0&-3&1&-2
    \end{array}
    \right].
    $$

    Divide the second row by $-3$:

    $$
    \left[
    \begin{array}{cc|cc}
    1&2&0&1\\
    0&1&-\frac13&\frac23
    \end{array}
    \right].
    $$

    Finally, perform $R_1\leftarrow R_1-2R_2$:

    $$
    \left[
    \begin{array}{cc|cc}
    1&0&\frac23&-\frac13\\
    0&1&-\frac13&\frac23
    \end{array}
    \right].
    $$

    Hence,

    $$
    S^{-1}=
    \begin{pmatrix}
    \frac23&-\frac13\\
    -\frac13&\frac23
    \end{pmatrix}
    =
    \frac13
    \begin{pmatrix}
    2&-1\\
    -1&2
    \end{pmatrix}.
    $$

d. We verify that

    $$
    SS^{-1}
    =
    \begin{pmatrix}
    2&1\\
    1&2
    \end{pmatrix}
    \frac13
    \begin{pmatrix}
    2&-1\\
    -1&2
    \end{pmatrix}
    =
    \frac13
    \begin{pmatrix}
    3&0\\
    0&3
    \end{pmatrix}
    =
    \begin{pmatrix}
    1&0\\
    0&1
    \end{pmatrix}.
    $$

    Thus the inverse is correct.


### Solution to @exr-gaussian-elimination-write-down-dual-basis {.unnumbered}



*The source does not supply a solution.*

### Solution to @exr-gaussian-elimination-robert-beezer-consider-following-system-equations {.unnumbered}

Using elementary operations, we get the augmented matrix $$\begin{bmatrix} 1 & 0 & 0 & 0 & 1 \\ 0 & 1 & 0 & 0 & -3 \\ 0 & 0 & 1 & 0 & -4 \\ 0 & 0 & 0 & 1 & 1 \end{bmatrix}.$$ The solution is unique: $x_1=1$, $x_2=-3$, $x_3=-4$, and $x_4=1$. Thus $$S=\{[1,-3,-4,1]^T\}.$$

### Solution to @exr-gaussian-elimination-robert-beezer-find-all-possible-solutions {.unnumbered}

By elementary row operations, we obtain the augmented matrix: $$\begin{bmatrix} 1 & 0 & 1 & 4/5 & 0 \\ 0 & 1 & -1 & -1/10 & 0 \\ 0 & 0 & 0 & 0 & 1 \end{bmatrix}$$ The last row represents the equation $0=1$, so there cannot be a solution to the system. $S = \{ \} = \emptyset$.

### Solution to @exr-gaussian-elimination-robert-beezer-find-all-possible-solutions-2 {.unnumbered}

The augmented matrix reduces to $$\begin{pmatrix} 1 & 2 & 0 & -4 & 2 \\ 0 & 0 & 1 & 3 & -6 \\ 0 & 0 & 0 & 0 & 0 \end{pmatrix}.$$ Hence $x_2$ and $x_4$ are free, while $$x_1=-2x_2+4x_4+2,\qquad x_3=-3x_4-6.$$ The solution set is

$$
S=\{[-2x_2+4x_4+2,x_2,-3x_4-6,x_4]^T\mid x_2,x_4\in\mathbb{F}\}.
$$

### Solution to @exr-gaussian-elimination-basis-basis-matrix-whose-columns-precisely {.unnumbered}

We know that the overlap matrix should be key here. So we multiply with $B^T$ from the left to get $B^T B \mathbf{x} = B^T \mathbf{y}$. Thus, $$\mathbf{x} = S^{-1} B^T \mathbf{y}.$$ We know that the overlap matrix $S = B^T B$ is invertible, since $B$ is a basis matrix.

### Solution to @exr-gaussian-elimination-linearly-independent-vectors-given-write-down {.unnumbered}

The dual basis $\tilde{B} = [\tilde{\mathbf{b}}_1, \cdots \tilde{\mathbf{b}}_n]$ is such that $\left\langle\tilde{\mathbf{b}}_i,\mathbf{b}_j\right\rangle = \delta_{ij}$. We obtain the equation $$\tilde{B}^H B = I.$$ Thus, $$\tilde{B} = (B^{-1})^H.$$

:::
