# Recommended exercises for the first day {.unnumbered}

This chapter contains recommended exercises for the mathematics
tutorial on the first day of the school. These recommended exercises are
considered especially useful.

We provide also a list of recommended exercises for the 'beginners'. If you
feel that you need training in the _absolute basics_ of the mathematics used
in quantum chemistry, we recommend that you start here.

In the next chapter, we provide lists of recommended exercises for each 
quantum chemistry topic taught at the school. 


<!-- BEGIN GENERATED RECOMMENDED EXERCISES -->
## Basic exercises recommended for beginners

- @exr-sets-and-functions-write-days-week-set
- @exr-sets-potential-energy-curve

## Recommended exercises

- @exr-sets-and-functions-write-five-first-natural-numbers-set
- @exr-sets-and-functions-draw-picture-representing-whole-sheet-overlapping
- @exr-molecule-sets
- @exr-cardinality-and-countability-explicitly-constructing-bijection
- @exr-general-vector-spaces-general-vector-spaces
- @exr-vectors-and-matrices-gaussian-elimination-compute-coefficients-such-illustrate
- @exr-vectors-and-matrices-person-walks-home-first-they-walk
- @exr-vectors-and-matrices-matrix-products-between-pairs-these-matrices
- @exr-vectors-and-matrices-matrix-defined-zero-otherwise-compute-action
- @exr-gaussian-elimination-robert-beezer-consider-following-system-equations
- @exr-polynomial-vector-spaces-set-all-polynomials-degree-less-than
- @exr-polynomial-vector-spaces-differentiation-operator-i-e-indeed-linear
- @exr-metric-spaces-metric-spaces
- @exr-visualizing-functions-path-defined-sketch-curve-traced-path
- @exr-visualizing-functions-sketch-level-curves
- @exr-continuity-and-differentiability-given-does-limit-not-exist-why
- @exr-continuity-and-differentiability-marsden-tromba-does-exist-if-you
- @exr-complex-arithmetic-compute-real-imaginary-parts-functions
- @exr-complex-arithmetic-complex-numbers-can-written-polar-form
- @exr-complex-arithmetic-illustrate-addition-coordinate-system-parallelogram-rule
- @exr-complex-sets-exercise
- @exr-singularities-and-contour-integrals-consider-function-how-many-poles-does

## Exercises for the curious

- @exr-complex-vector-space-complex-numbers-real-vector-space
- @exr-eigenvalues-and-diagonalization-eigenvalue-decomposition
- @exr-gram-schmidt-gram-schmidt-orthogonalization
- @exr-singular-value-decomposition-singular-value-decomposition-compression-tool
- @exr-dual-numbers-dual-numbers
- @exr-complex-step-differentiation-complex-step-method

<!-- END GENERATED RECOMMENDED EXERCISES -->
